# Generated by Django 3.2 on 2023-01-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='created_on',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='accepted_privacy_policy',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='registered_user',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribed',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='updated_on',
        ),
    ]
